# Issue 10277: random_prime() fails to work for values > 2^40 if a lower bound is set

archive/issues_010276.json:
```json
{
    "assignees": [
        "https://github.com/williamstein"
    ],
    "body": "`random_prime()` appears to handle quite large numbers\n\n```\nsage: random_prime(10^100)\n7980458528200352285375353724908005160633013691189804269781978682382158576820070695791880087837726879\n```\n\nin fact, it appears to as though it will work to at least 10<sup>1000000000</sup>, though it fails for 10<sup>10000000000</sup>. \n\nBut if a lower bound is set, the upper limit of `random_prime` is restricted to 2<sup>40</sup>, which is around 10<sup>12</sup>. \n\n```\nsage: random_prime(2^40+1,lbound=12)\n---------------------------------------------------------------------------\nNotImplementedError                       Traceback (most recent call last)\n\n/export/home/drkirkby/qq/sage-4.6.1.alpha1/<ipython console> in <module>()\n\n/export/home/drkirkby/qq/sage-4.6.1.alpha1/local/lib/python2.6/site-packages/sage/rings/arith.pyc in random_prime(n, proof, lbound)\n   1159         return n\n   1160     lbound = max(2, lbound)\n-> 1161     if lbound > 2 and prime_pi(n) <= prime_pi(lbound-1):\n   1162         raise ValueError, \"There are no primes between %s and %s (inclusive)\" % (lbound, n)\n   1163     else:\n\n/export/home/drkirkby/qq/sage-4.6.1.alpha1/local/lib/python2.6/site-packages/sage/functions/prime_pi.so in sage.functions.prime_pi.PrimePi.__call__ (sage/functions/prime_pi.c:1125)()\n\nNotImplementedError: computation of prime_pi() greater 2**40 not implemented\n```\n\nIf I compare this with Mathematica 7.01, I find Mathematica has no such problems generating random primes up to large values, even if a lower bound is set. Here's a random prime in the range 1000 to 10<sup>1000</sup>\n\n```\nIn[1]:= RandomPrime[{1000,10^1000}]\n\nOut[1]= 113385181521900468164191823243380715126145463788185407100720218734056\\\n \n>    479220211608218084498402183236351542265593400216896042171731891088681371\\\n \n>    031933937779910290752183096697533115893317148489651228723855774549826488\\\n \n>    609183869775506555260353444625540357377478392480383926781924074661958405\\\n \n>    927348714375837006129760795638915099524015590322046363160083139499201107\\\n \n>    644734466583958699690474658383854230153477004091701453047153516742596851\\\n \n>    834894247750217438643934960127478251140350389220934422153161054330077533\\\n \n>    489023104217807807159360316591672041363249441395509536046012375037619063\\\n \n>    643233350748848129475142877253717443233362740964522093581092785244209404\\\n \n>    408239930373701630354570762373539217835019703894617890496967417800477778\\\n \n>    280004392636751979356175924773816944978114099526161921816188057377506083\\\n \n>    674761134810672819835357486060679152139402595701113409894341135150001602\\\n \n>    855079098938140261704512228583255998916339884372871399317049545813648006\\\n \n>    9788852836452583334765209656025537275350871626318478286244659000299\n```\n\nBTW, Mathematica is **much** faster too. I gave up trying to get a random prime in Sage up to 10<sup>1000</sup> \n\n```\nsage: time random_prime(10^1000)\n\n```\n\nafter spending more than 16 minutes of CPU time, whereas Mathematica can generate such a random prime in 7 seconds. \n\n(Part of this might be due to the fact this is a 32-bit version of Sage vs a 64-bit version of Mathematica, but I doubt that explains a factor of more than 130)\n\nDave \n\nComponent: **number theory**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/10277_\n\n",
    "closed_at": "2010-11-17T02:20:44Z",
    "created_at": "2010-11-16T01:09:04Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/bug",
        "https://github.com/sagemath/sage/labels/c%3A%20number%20theory",
        "https://github.com/sagemath/sage/labels/invalid"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "random_prime() fails to work for values > 2^40 if a lower bound is set",
    "type": "issue",
    "updated_at": "2010-11-17T06:50:20Z",
    "url": "https://github.com/sagemath/sage/issues/10277",
    "user": "https://github.com/sagetrac-drkirkby"
}
```
`random_prime()` appears to handle quite large numbers

```
sage: random_prime(10^100)
7980458528200352285375353724908005160633013691189804269781978682382158576820070695791880087837726879
```

in fact, it appears to as though it will work to at least 10<sup>1000000000</sup>, though it fails for 10<sup>10000000000</sup>. 

But if a lower bound is set, the upper limit of `random_prime` is restricted to 2<sup>40</sup>, which is around 10<sup>12</sup>. 

```
sage: random_prime(2^40+1,lbound=12)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)

/export/home/drkirkby/qq/sage-4.6.1.alpha1/<ipython console> in <module>()

/export/home/drkirkby/qq/sage-4.6.1.alpha1/local/lib/python2.6/site-packages/sage/rings/arith.pyc in random_prime(n, proof, lbound)
   1159         return n
   1160     lbound = max(2, lbound)
-> 1161     if lbound > 2 and prime_pi(n) <= prime_pi(lbound-1):
   1162         raise ValueError, "There are no primes between %s and %s (inclusive)" % (lbound, n)
   1163     else:

/export/home/drkirkby/qq/sage-4.6.1.alpha1/local/lib/python2.6/site-packages/sage/functions/prime_pi.so in sage.functions.prime_pi.PrimePi.__call__ (sage/functions/prime_pi.c:1125)()

NotImplementedError: computation of prime_pi() greater 2**40 not implemented
```

If I compare this with Mathematica 7.01, I find Mathematica has no such problems generating random primes up to large values, even if a lower bound is set. Here's a random prime in the range 1000 to 10<sup>1000</sup>

```
In[1]:= RandomPrime[{1000,10^1000}]

Out[1]= 113385181521900468164191823243380715126145463788185407100720218734056\
 
>    479220211608218084498402183236351542265593400216896042171731891088681371\
 
>    031933937779910290752183096697533115893317148489651228723855774549826488\
 
>    609183869775506555260353444625540357377478392480383926781924074661958405\
 
>    927348714375837006129760795638915099524015590322046363160083139499201107\
 
>    644734466583958699690474658383854230153477004091701453047153516742596851\
 
>    834894247750217438643934960127478251140350389220934422153161054330077533\
 
>    489023104217807807159360316591672041363249441395509536046012375037619063\
 
>    643233350748848129475142877253717443233362740964522093581092785244209404\
 
>    408239930373701630354570762373539217835019703894617890496967417800477778\
 
>    280004392636751979356175924773816944978114099526161921816188057377506083\
 
>    674761134810672819835357486060679152139402595701113409894341135150001602\
 
>    855079098938140261704512228583255998916339884372871399317049545813648006\
 
>    9788852836452583334765209656025537275350871626318478286244659000299
```

BTW, Mathematica is **much** faster too. I gave up trying to get a random prime in Sage up to 10<sup>1000</sup> 

```
sage: time random_prime(10^1000)

```

after spending more than 16 minutes of CPU time, whereas Mathematica can generate such a random prime in 7 seconds. 

(Part of this might be due to the fact this is a 32-bit version of Sage vs a 64-bit version of Mathematica, but I doubt that explains a factor of more than 130)

Dave 

Component: **number theory**

_Issue created by migration from https://trac.sagemath.org/ticket/10277_





---

archive/issue_events_135585.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-16T01:09:04Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "milestone_number": null,
    "milestone_title": "sage-4.6.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135585"
}
```



---

archive/issue_events_135586.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-16T01:09:04Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20number%20theory",
    "label_color": "0000ff",
    "label_name": "c: number theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135586"
}
```



---

archive/issue_events_135587.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-16T01:09:04Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135587"
}
```



---

archive/issue_events_135588.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-16T01:09:04Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135588"
}
```



---

archive/issue_events_135589.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2010-11-16T01:09:04Z",
    "event": "assigned",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "subject": "https://github.com/sagetrac-drkirkby",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135589"
}
```



---

archive/issue_comments_095863.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\n(1) The performance comparison to Mathematica is invalid since Mathematica only returns a pseudoprime, and for that (proof=False), sage is actually much faster than Mathematica already.\n\n(2) On both 32 and 64-bit Linux I can not reproduce this. \n\n```\n\nsage: random_prime(2^40+1,lbound=12)\n477618500201\nsage: sys.maxint\n2147483647\n```\n\nAnd reading the source code I can't see what this has to do with prime_pi.  I'm tempted to mark this ticket invalid if there isn't further info.",
    "created_at": "2010-11-16T07:11:27Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/10277#issuecomment-95863",
    "user": "https://github.com/williamstein"
}
```

<div id="comment:1" align="right">comment:1</div>

(1) The performance comparison to Mathematica is invalid since Mathematica only returns a pseudoprime, and for that (proof=False), sage is actually much faster than Mathematica already.

(2) On both 32 and 64-bit Linux I can not reproduce this. 

```

sage: random_prime(2^40+1,lbound=12)
477618500201
sage: sys.maxint
2147483647
```

And reading the source code I can't see what this has to do with prime_pi.  I'm tempted to mark this ticket invalid if there isn't further info.



---

archive/issue_events_135590.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-17T02:20:44Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135590"
}
```



---

archive/issue_events_135591.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-17T02:20:44Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135591"
}
```



---

archive/issue_events_135592.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-17T02:20:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "label": "https://github.com/sagemath/sage/labels/invalid",
    "label_color": "c6c6c6",
    "label_name": "invalid",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135592"
}
```



---

archive/issue_comments_095864.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nprime_pi was being called as a result of a bug in the patch at #10112. Since that patch has never been committed to Sage, it is indeed an invalid bug report. I'm closing it as invalid.",
    "created_at": "2010-11-17T02:20:44Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/10277#issuecomment-95864",
    "user": "https://github.com/sagetrac-drkirkby"
}
```

<div id="comment:2" align="right">comment:2</div>

prime_pi was being called as a result of a bug in the patch at #10112. Since that patch has never been committed to Sage, it is indeed an invalid bug report. I'm closing it as invalid.



---

archive/issue_events_135593.json:
```json
{
    "actor": "https://github.com/sagetrac-drkirkby",
    "created_at": "2010-11-17T02:20:44Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "milestone_number": null,
    "milestone_title": "sage-4.6.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/10277#event-135593"
}
```



---

archive/issue_comments_095865.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\n> prime_pi was being called as a result of a bug in the patch at #10112. Since that patch has never\n>  been committed to Sage, it is indeed an invalid bug report. I'm closing it as invalid.\n\nVery good work tracking this down.  I'm really glad 10112 didn't go in as posted.  That would have been pretty ironic to compute prime_pi just to generate an error message!  Great work again on this.",
    "created_at": "2010-11-17T06:50:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/10277",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/10277#issuecomment-95865",
    "user": "https://github.com/williamstein"
}
```

<div id="comment:3" align="right">comment:3</div>

> prime_pi was being called as a result of a bug in the patch at #10112. Since that patch has never
>  been committed to Sage, it is indeed an invalid bug report. I'm closing it as invalid.

Very good work tracking this down.  I'm really glad 10112 didn't go in as posted.  That would have been pretty ironic to compute prime_pi just to generate an error message!  Great work again on this.
