# Issue 18141: list(ZZ) --> infinite loop

archive/issues_018141.json:
```json
{
    "body": "CC:  @videlec\n\nFor some reason, `list(something)` breaks if `__len__` raises a `NotImplementedError`, but `__len__` is ignored if a `TypeError` is returned.\n\nPython....\n\nAs `len(NN)` already raises a `NotImplementedError` I just copied the behaviour.\n\nNathann\n\nIssue created by migration from https://trac.sagemath.org/ticket/18378\n\n",
    "created_at": "2015-05-07T16:14:25Z",
    "labels": [
        "component: basic arithmetic",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-6.7",
    "title": "list(ZZ) --> infinite loop",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/18141",
    "user": "https://github.com/nathanncohen"
}
```
CC:  @videlec

For some reason, `list(something)` breaks if `__len__` raises a `NotImplementedError`, but `__len__` is ignored if a `TypeError` is returned.

Python....

As `len(NN)` already raises a `NotImplementedError` I just copied the behaviour.

Nathann

Issue created by migration from https://trac.sagemath.org/ticket/18378





---

archive/issue_comments_244342.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2015-05-07T16:16:12Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244342",
    "user": "https://github.com/nathanncohen"
}
```

Changing status from new to needs_review.



---

archive/issue_comments_244343.json:
```json
{
    "body": "Branch pushed to git repo; I updated commit sha1. New commits:",
    "created_at": "2015-05-07T16:16:40Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244343",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

Branch pushed to git repo; I updated commit sha1. New commits:



---

archive/issue_comments_244344.json:
```json
{
    "body": "For posterity, the reason that `TypeError` gets caught is to make this work:\n\n```\nsage: l=(i for i in range(10))\nsage: len(l)\nTypeError: object of type 'generator' has no len()\nsage: list(l)\n[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n```\n\nIt may well be an accident that `list` checks `len` of its argument before it checks if it's iterable, so I would not consider changing the error type a reliable way to prevent an infinite loop. I don't think python officially supports a way of preventing `list(<infinite iterable>)` from going in an infinite loop. It works, though...",
    "created_at": "2015-05-07T16:35:47Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244344",
    "user": "https://github.com/nbruin"
}
```

For posterity, the reason that `TypeError` gets caught is to make this work:

```
sage: l=(i for i in range(10))
sage: len(l)
TypeError: object of type 'generator' has no len()
sage: list(l)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

It may well be an accident that `list` checks `len` of its argument before it checks if it's iterable, so I would not consider changing the error type a reliable way to prevent an infinite loop. I don't think python officially supports a way of preventing `list(<infinite iterable>)` from going in an infinite loop. It works, though...



---

archive/issue_comments_244345.json:
```json
{
    "body": "> It may well be an accident that `list` checks `len` of its argument before it checks if it's iterable, so I would not consider changing the error type a reliable way to prevent an infinite loop. I don't think python officially supports a way of preventing `list(<infinite iterable>)` from going in an infinite loop.\n\nOh I see. Thanks `;-)`",
    "created_at": "2015-05-07T17:46:50Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244345",
    "user": "https://github.com/nathanncohen"
}
```

> It may well be an accident that `list` checks `len` of its argument before it checks if it's iterable, so I would not consider changing the error type a reliable way to prevent an infinite loop. I don't think python officially supports a way of preventing `list(<infinite iterable>)` from going in an infinite loop.

Oh I see. Thanks `;-)`



---

archive/issue_comments_244346.json:
```json
{
    "body": "Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:",
    "created_at": "2015-05-07T19:24:05Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244346",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:



---

archive/issue_comments_244347.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2015-05-18T20:34:37Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244347",
    "user": "https://trac.sagemath.org/admin/accounts/users/jpflori"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_comments_244348.json:
```json
{
    "body": "Looks good enough to me, especially if `NN` already behaves like this.",
    "created_at": "2015-05-18T20:34:37Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244348",
    "user": "https://trac.sagemath.org/admin/accounts/users/jpflori"
}
```

Looks good enough to me, especially if `NN` already behaves like this.



---

archive/issue_comments_244349.json:
```json
{
    "body": "Thanks !\n\nNathann",
    "created_at": "2015-05-18T20:36:04Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244349",
    "user": "https://github.com/nathanncohen"
}
```

Thanks !

Nathann



---

archive/issue_events_017395.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2015-05-19T22:07:37Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/18141#event-17395"
}
```



---

archive/issue_comments_244350.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2015-05-19T22:07:37Z",
    "issue": "https://github.com/sagemath/sagetest/issues/18141",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/18141#issuecomment-244350",
    "user": "https://github.com/vbraun"
}
```

Resolution: fixed
