# Issue 29251: plot3d method of Graphics objects broken with threejs

archive/issues_029014.json:
```json
{
    "body": "As reported in https://ask.sagemath.org/question/50051/, 3d objects constructed by the method `plot3d()` of class `Graphics` do not display properly with `threejs`. A minimal example is\n\n```\nsage: g = plot(sin(x), (x, 0, 2*pi))\nsage: g.plot3d()\n/home/eric/sage/9.1.develop/local/lib/python3.7/site-packages/sage/repl/rich_output/display_manager.py:592: \nRichReprWarning: Exception in _rich_repr_ while displaying object: \n'Line' object has no attribute 'all'\n  RichReprWarning,\n```\nNote that\n\n```\nsage: show(g.plot3d(), viewer='jmol')\nLaunched jmol viewer for Graphics3d Object\n```\nworks well.\nBesides, if one change the value of the argument `z` from `0` (the default) to `2`:\n\n```\nsage: g.plot3d(z=2)\nLaunched html viewer for Graphics3d Object\n```\none does not get any error message but a wrong threejs display: the curve is located at z=-2 instead of z=2.\n\nCC:  @paulmasson\n\nKeywords: graphics, plot3d, threejs\n\nReviewer: Paul Masson, Eric Gourgoulhon\n\nDependencies: #29227\n\nResolution: duplicate\n\nIssue created by migration from https://trac.sagemath.org/ticket/29251\n\n",
    "closed_at": "2020-03-25T19:38:46Z",
    "created_at": "2020-02-27T12:51:07Z",
    "labels": [
        "component: graphics",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-duplicate/invalid/wontfix",
    "title": "plot3d method of Graphics objects broken with threejs",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/29251",
    "user": "https://github.com/egourgoulhon"
}
```
As reported in https://ask.sagemath.org/question/50051/, 3d objects constructed by the method `plot3d()` of class `Graphics` do not display properly with `threejs`. A minimal example is

```
sage: g = plot(sin(x), (x, 0, 2*pi))
sage: g.plot3d()
/home/eric/sage/9.1.develop/local/lib/python3.7/site-packages/sage/repl/rich_output/display_manager.py:592: 
RichReprWarning: Exception in _rich_repr_ while displaying object: 
'Line' object has no attribute 'all'
  RichReprWarning,
```
Note that

```
sage: show(g.plot3d(), viewer='jmol')
Launched jmol viewer for Graphics3d Object
```
works well.
Besides, if one change the value of the argument `z` from `0` (the default) to `2`:

```
sage: g.plot3d(z=2)
Launched html viewer for Graphics3d Object
```
one does not get any error message but a wrong threejs display: the curve is located at z=-2 instead of z=2.

CC:  @paulmasson

Keywords: graphics, plot3d, threejs

Reviewer: Paul Masson, Eric Gourgoulhon

Dependencies: #29227

Resolution: duplicate

Issue created by migration from https://trac.sagemath.org/ticket/29251





---

archive/issue_comments_437363.json:
```json
{
    "body": "<a id='comment:2'></a>Will be fixed by #29227",
    "created_at": "2020-03-19T21:16:45Z",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/29251#issuecomment-437363",
    "user": "https://github.com/paulmasson"
}
```

<a id='comment:2'></a>Will be fixed by #29227



---

archive/issue_comments_437364.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2020-03-22T21:51:11Z",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/29251#issuecomment-437364",
    "user": "https://github.com/paulmasson"
}
```

Changing status from new to needs_review.



---

archive/issue_events_074376.json:
```json
{
    "actor": "https://github.com/paulmasson",
    "created_at": "2020-03-22T21:51:11Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "milestone": "sage-duplicate/invalid/wontfix",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/29251#event-74376"
}
```



---

archive/issue_comments_437365.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2020-03-23T08:02:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/29251#issuecomment-437365",
    "user": "https://github.com/egourgoulhon"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_comments_437366.json:
```json
{
    "body": "<a id='comment:4'></a>I confirm that the issue reported here is fixed by #29227.",
    "created_at": "2020-03-23T08:02:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/29251#issuecomment-437366",
    "user": "https://github.com/egourgoulhon"
}
```

<a id='comment:4'></a>I confirm that the issue reported here is fixed by #29227.



---

archive/issue_events_074377.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-03-25T19:38:46Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/29251#event-74377"
}
```



---

archive/issue_comments_437367.json:
```json
{
    "body": "Resolution: duplicate",
    "created_at": "2020-03-25T19:38:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/29251",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/29251#issuecomment-437367",
    "user": "https://github.com/fchapoton"
}
```

Resolution: duplicate
