# Issue 22834: infinite recursion in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__

archive/issues_022597.json:
```json
{
    "body": "Division by zero in `CIF` leads to infinite recursion:\n\n```\nsage: ~CIF(RIF(-1,1))\n---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\n<ipython-input-4-7c8464c26127> in <module>()\n----> 1 ~CIF(RIF(-Integer(1),Integer(1)))\n\n/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n   1290             return -I*(-I*self).__invert__()\n   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n-> 1292             return -(-self).__invert__()\n   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n   1294             I = self.parent().gen(0)\n\n... last 1 frames repeated, from the frame below ...\n\n/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n   1290             return -I*(-I*self).__invert__()\n   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n-> 1292             return -(-self).__invert__()\n   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n   1294             I = self.parent().gen(0)\n\nRuntimeError: maximum recursion depth exceeded while calling a Python object\n```\n\nThe bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n\n```\n        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n            return -(-self).__invert__()\n```\n\nwhich looks like it can fail in that way if the signs are zero.\n\nMinor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.\n\nCC:  @miguelmarco\n\nStatus: new\n\nIssue created by migration from https://trac.sagemath.org/ticket/22834\n\n",
    "created_at": "2017-04-19T18:44:52Z",
    "labels": [
        "component: basic arithmetic",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-8.0",
    "title": "infinite recursion in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/22834",
    "user": "https://trac.sagemath.org/admin/accounts/users/wonder"
}
```
Division by zero in `CIF` leads to infinite recursion:

```
sage: ~CIF(RIF(-1,1))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7c8464c26127> in <module>()
----> 1 ~CIF(RIF(-Integer(1),Integer(1)))

/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
   1290             return -I*(-I*self).__invert__()
   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
-> 1292             return -(-self).__invert__()
   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
   1294             I = self.parent().gen(0)

... last 1 frames repeated, from the frame below ...

/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
   1290             return -I*(-I*self).__invert__()
   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
-> 1292             return -(-self).__invert__()
   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
   1294             I = self.parent().gen(0)

RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):

```
        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
            return -(-self).__invert__()
```

which looks like it can fail in that way if the signs are zero.

Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.

CC:  @miguelmarco

Status: new

Issue created by migration from https://trac.sagemath.org/ticket/22834





---

archive/issue_comments_335694.json:
```json
{
    "body": "<a id='comment:1'></a>Calling N() before comparing to zero seems to be a usable workaround",
    "created_at": "2017-04-19T18:48:14Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335694",
    "user": "https://trac.sagemath.org/admin/accounts/users/wonder"
}
```

<a id='comment:1'></a>Calling N() before comparing to zero seems to be a usable workaround



---

archive/issue_comments_335695.json:
```json
{
    "body": "<a id='comment:2'></a>Do you have a complete example?",
    "created_at": "2017-04-20T08:46:40Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335695",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:2'></a>Do you have a complete example?



---

archive/issue_comments_335696.json:
```json
{
    "body": "Changing component from number fields to basic arithmetic.",
    "created_at": "2017-04-20T08:51:02Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335696",
    "user": "https://github.com/jdemeyer"
}
```

Changing component from number fields to basic arithmetic.



---

archive/issue_events_059350.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-20T08:51:02Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "milestone": "sage-8.0",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/22834#event-59350"
}
```



---

archive/issue_comments_335697.json:
```json
{
    "body": "Description changed:\n```diff\n--- \n+++ \n@@ -1,13 +1,32 @@\n-It is possible to crash sage with an infinite recursion by comparing a number to zero:\n+Division by zero in `CIF` leads to infinite recursion:\n \n ```\n-...\n-  File \"sage/rings/complex_interval.pyx\", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)\n-  File \"sage/rings/complex_interval.pyx\", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)\n+sage: ~CIF(RIF(-1,1))\n+---------------------------------------------------------------------------\n+RuntimeError                              Traceback (most recent call last)\n+<ipython-input-4-7c8464c26127> in <module>()\n+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n+... last 1 frames repeated, from the frame below ...\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n RuntimeError: maximum recursion depth exceeded while calling a Python object\n ```\n \n-It looks like this came up in my code when comparing an algebraic number to zero, but the bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n \n ```\n         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n@@ -16,6 +35,7 @@\n \n which looks like it can fail in that way if the signs are zero.\n \n+\n Comment: 1\n \n Component: number fields\n```\n",
    "created_at": "2017-04-20T08:51:02Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335697",
    "user": "https://github.com/jdemeyer"
}
```

Description changed:
```diff
--- 
+++ 
@@ -1,13 +1,32 @@
-It is possible to crash sage with an infinite recursion by comparing a number to zero:
+Division by zero in `CIF` leads to infinite recursion:
 
 ```
-...
-  File "sage/rings/complex_interval.pyx", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)
-  File "sage/rings/complex_interval.pyx", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)
+sage: ~CIF(RIF(-1,1))
+---------------------------------------------------------------------------
+RuntimeError                              Traceback (most recent call last)
+<ipython-input-4-7c8464c26127> in <module>()
+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
+... last 1 frames repeated, from the frame below ...
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
 RuntimeError: maximum recursion depth exceeded while calling a Python object
 ```
 
-It looks like this came up in my code when comparing an algebraic number to zero, but the bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):
+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):
 
 ```
         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
@@ -16,6 +35,7 @@
 
 which looks like it can fail in that way if the signs are zero.
 
+
 Comment: 1
 
 Component: number fields
```




---

archive/issue_comments_335698.json:
```json
{
    "body": "Description changed:\n```diff\n--- \n+++ \n@@ -1,4 +1,41 @@\n+Division by zero in `CIF` leads to infinite recursion:\n \n+```\n+sage: ~CIF(RIF(-1,1))\n+---------------------------------------------------------------------------\n+RuntimeError                              Traceback (most recent call last)\n+<ipython-input-4-7c8464c26127> in <module>()\n+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n+... last 1 frames repeated, from the frame below ...\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n+RuntimeError: maximum recursion depth exceeded while calling a Python object\n+```\n+\n+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n+\n+```\n+        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+            return -(-self).__invert__()\n+```\n+\n+which looks like it can fail in that way if the signs are zero.\n+\n+Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.\n \n Comment: 1\n \n```\n",
    "created_at": "2017-04-20T08:53:43Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335698",
    "user": "https://github.com/jdemeyer"
}
```

Description changed:
```diff
--- 
+++ 
@@ -1,4 +1,41 @@
+Division by zero in `CIF` leads to infinite recursion:
 
+```
+sage: ~CIF(RIF(-1,1))
+---------------------------------------------------------------------------
+RuntimeError                              Traceback (most recent call last)
+<ipython-input-4-7c8464c26127> in <module>()
+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
+... last 1 frames repeated, from the frame below ...
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
+RuntimeError: maximum recursion depth exceeded while calling a Python object
+```
+
+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):
+
+```
+        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+            return -(-self).__invert__()
+```
+
+which looks like it can fail in that way if the signs are zero.
+
+Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.
 
 Comment: 1
 
```




---

archive/issue_comments_335699.json:
```json
{
    "body": "<a id='comment:5'></a>Works now\n\n```\n\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510\n\u2502 SageMath version 9.1.rc4, Release Date: 2020-05-09                 \u2502\n\u2502 Using Python 3.7.3. Type \"help()\" for help.                        \u2502\n\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518\n\u250f\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2513\n\u2503 Warning: this is a prerelease version, and it may be unstable.     \u2503\n\u2517\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u251b\nsage: ~CIF(RIF(-1,1))\n[.. NaN ..] + [.. NaN ..]*I\n```",
    "created_at": "2020-05-13T15:37:27Z",
    "issue": "https://github.com/sagemath/sagetest/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/22834#issuecomment-335699",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:5'></a>Works now

```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.1.rc4, Release Date: 2020-05-09                 │
│ Using Python 3.7.3. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: ~CIF(RIF(-1,1))
[.. NaN ..] + [.. NaN ..]*I
```
