# Issue 24698: fixing one plantri doctest

archive/issues_024461.json:
```json
{
    "assignees": [],
    "body": "Future division made a doctest failure with the optional package plantri installed\n\n```\nsage -t --long src/sage/graphs/graph_generators.py\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    [u for u in list(gen)]  # optional plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n        [u for u in list(gen)]  # optional plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n    NameError: name 'planar' is not defined\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes == dual_planar_sizes                      # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n        planar_sizes == dual_planar_sizes                      # optional -- plantri\n    NameError: name 'planar_sizes' is not defined\n**********************************************************************\n1 item had failures:\n   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n    [140 tests, 4 failures, 29.80 s]\n```\n\nCC:  @tscrim @embray @jdemeyer\n\nBranch/Commit: **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**\n\nReviewer: **Travis Scrimshaw**\n\nAuthor: **Fr\u00e9d\u00e9ric Chapoton**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/24698_\n\n",
    "closed_at": "2018-02-16T23:39:03Z",
    "created_at": "2018-02-09T16:52:43Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/component%3A%20graph%20theory",
        "https://github.com/sagemath/sage/labels/p1%20%E2%80%93%20blocker",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.2",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "fixing one plantri doctest",
    "type": "issue",
    "updated_at": "2018-02-16T23:39:03Z",
    "url": "https://github.com/sagemath/sage/issues/24698",
    "user": "https://github.com/fchapoton"
}
```
Future division made a doctest failure with the optional package plantri installed

```
sage -t --long src/sage/graphs/graph_generators.py
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    [u for u in list(gen)]  # optional plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
        [u for u in list(gen)]  # optional plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
    NameError: name 'planar' is not defined
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes == dual_planar_sizes                      # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
        planar_sizes == dual_planar_sizes                      # optional -- plantri
    NameError: name 'planar_sizes' is not defined
**********************************************************************
1 item had failures:
   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
    [140 tests, 4 failures, 29.80 s]
```

CC:  @tscrim @embray @jdemeyer

Branch/Commit: **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**

Reviewer: **Travis Scrimshaw**

Author: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/24698_





---

archive/issue_events_323925.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "milestone_number": null,
    "milestone_title": "sage-8.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323925"
}
```



---

archive/issue_events_323926.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/component%3A%20graph%20theory",
    "label_color": "0000ff",
    "label_name": "component: graph theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323926"
}
```



---

archive/issue_events_323927.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p3%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323927"
}
```



---

archive/issue_events_323928.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "696969",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323928"
}
```



---

archive/issue_comments_378049.json:
```json
{
    "body": "Branch: **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378049",
    "user": "https://github.com/fchapoton"
}
```

Branch: **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**



---

archive/issue_events_323929.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:53:26Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323929"
}
```



---

archive/issue_comments_378050.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">Comment 1</div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378050",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:1" align="right">Comment 1</div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_comments_378051.json:
```json
{
    "body": "Commit: **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378051",
    "user": "https://github.com/fchapoton"
}
```

Commit: **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**



---

archive/issue_events_323930.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323930"
}
```



---

archive/issue_events_323931.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323931"
}
```



---

archive/issue_comments_378052.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">Comment 2</div>\n\nLGTM.",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378052",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:2" align="right">Comment 2</div>

LGTM.



---

archive/issue_comments_378053.json:
```json
{
    "body": "Reviewer: **Travis Scrimshaw**",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378053",
    "user": "https://github.com/tscrim"
}
```

Reviewer: **Travis Scrimshaw**



---

archive/issue_events_323932.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323932"
}
```



---

archive/issue_events_323933.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323933"
}
```



---

archive/issue_comments_378054.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">Comment 3</div>\n\nMerge conflict",
    "created_at": "2018-02-09T23:50:46Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378054",
    "user": "https://github.com/vbraun"
}
```

<div id="comment:3" align="right">Comment 3</div>

Merge conflict



---

archive/issue_comments_378055.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1 +1,69 @@\n-coming from future division\n+Future division made a doctest failure with the optional package plantri installed\n+\n+```\n+sage -t --long src/sage/graphs/graph_generators.py\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    [u for u in list(gen)]  # optional plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n+        [u for u in list(gen)]  # optional plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+    NameError: name 'planar' is not defined\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes == dual_planar_sizes                      # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n+        planar_sizes == dual_planar_sizes                      # optional -- plantri\n+    NameError: name 'planar_sizes' is not defined\n+**********************************************************************\n+1 item had failures:\n+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n+    [140 tests, 4 failures, 29.80 s]\n+```\n``````\n",
    "created_at": "2018-02-13T19:23:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378055",
    "user": "https://github.com/videlec"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1 +1,69 @@
-coming from future division
+Future division made a doctest failure with the optional package plantri installed
+
+```
+sage -t --long src/sage/graphs/graph_generators.py
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    [u for u in list(gen)]  # optional plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
+        [u for u in list(gen)]  # optional plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+    NameError: name 'planar' is not defined
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes == dual_planar_sizes                      # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
+        planar_sizes == dual_planar_sizes                      # optional -- plantri
+    NameError: name 'planar_sizes' is not defined
+**********************************************************************
+1 item had failures:
+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
+    [140 tests, 4 failures, 29.80 s]
+```
``````




---

archive/issue_events_323934.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-13T19:23:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p3%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323934"
}
```



---

archive/issue_events_323935.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-13T19:23:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p1%20%E2%80%93%20blocker",
    "label_color": "ff0000",
    "label_name": "p1 \u2013 blocker",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323935"
}
```



---

archive/issue_comments_378056.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">Comment 5</div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834\">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378056",
    "user": "https://github.com/videlec"
}
```

<div id="comment:5" align="right">Comment 5</div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>




---

archive/issue_comments_378057.json:
```json
{
    "body": "Changed commit from **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)** to **[d910d87](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)**",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378057",
    "user": "https://github.com/videlec"
}
```

Changed commit from **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)** to **[d910d87](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)**



---

archive/issue_events_323936.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323936"
}
```



---

archive/issue_events_323937.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323937"
}
```



---

archive/issue_comments_378058.json:
```json
{
    "body": "Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)**",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378058",
    "user": "https://github.com/videlec"
}
```

Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)**



---

archive/issue_events_323938.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323938"
}
```



---

archive/issue_events_323939.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323939"
}
```



---

archive/issue_comments_378059.json:
```json
{
    "body": "Changed commit from **[d910d87](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)** to **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378059",
    "user": "https://github.com/videlec"
}
```

Changed commit from **[d910d87](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)** to **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**



---

archive/issue_comments_378060.json:
```json
{
    "body": "<div id=\"comment:7\" align=\"right\">Comment 7</div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378060",
    "user": "https://github.com/videlec"
}
```

<div id="comment:7" align="right">Comment 7</div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_events_323940.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323940"
}
```



---

archive/issue_events_323941.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323941"
}
```



---

archive/issue_comments_378061.json:
```json
{
    "body": "Changed branch from **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)** to **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378061",
    "user": "https://github.com/videlec"
}
```

Changed branch from **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)** to **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**



---

archive/issue_comments_378062.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">Comment 8</div>\n\nReplying to [@vbraun](#comment%3A3):\n> Merge conflict\n\nSince this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...",
    "created_at": "2018-02-14T17:59:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378062",
    "user": "https://github.com/videlec"
}
```

<div id="comment:8" align="right">Comment 8</div>

Replying to [@vbraun](#comment%3A3):
> Merge conflict

Since this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...



---

archive/issue_comments_378063.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">Comment 9</div>\n\nIt is supposed to have a conflict with Volker's private branch. But looking at the file there:\n\nhttps://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py\n\nI really do not see how there could be any conflict. This file was last modified 3 weeks ago.",
    "created_at": "2018-02-14T18:41:45Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378063",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:9" align="right">Comment 9</div>

It is supposed to have a conflict with Volker's private branch. But looking at the file there:

https://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py

I really do not see how there could be any conflict. This file was last modified 3 weeks ago.



---

archive/issue_events_323942.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323942"
}
```



---

archive/issue_events_323943.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323943"
}
```



---

archive/issue_comments_378064.json:
```json
{
    "body": "<div id=\"comment:10\" align=\"right\">Comment 10</div>\n\nLet's try it again then.",
    "created_at": "2018-02-14T22:46:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378064",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:10" align="right">Comment 10</div>

Let's try it again then.



---

archive/issue_events_323944.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323944"
}
```



---

archive/issue_events_323945.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "d7195f1f358f0bbd7424a7c809914e0d144a43dc",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-323945"
}
```



---

archive/issue_comments_378065.json:
```json
{
    "body": "Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-16T23:39:03Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-378065",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[a09e8a6](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**
