# Issue 24698: fixing one plantri doctest

archive/issues_024461.json:
```json
{
    "assignees": [],
    "body": "Future division made a doctest failure with the optional package plantri installed\n\n```\nsage -t --long src/sage/graphs/graph_generators.py\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    [u for u in list(gen)]  # optional plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n        [u for u in list(gen)]  # optional plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n    NameError: name 'planar' is not defined\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes == dual_planar_sizes                      # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n        planar_sizes == dual_planar_sizes                      # optional -- plantri\n    NameError: name 'planar_sizes' is not defined\n**********************************************************************\n1 item had failures:\n   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n    [140 tests, 4 failures, 29.80 s]\n```\n\nCC:  @tscrim @embray @jdemeyer\n\nBranch/Commit: **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**\n\nReviewer: **Travis Scrimshaw**\n\nAuthor: **Fr\u00e9d\u00e9ric Chapoton**\n\nComponent: **graph theory**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/24698_\n\n",
    "closed_at": "2018-02-16T23:39:03Z",
    "created_at": "2018-02-09T16:52:43Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
        "https://github.com/sagemath/sage/labels/p%3A%201%20%E2%80%93%20blocker",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.2",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "fixing one plantri doctest",
    "type": "issue",
    "updated_at": "2018-02-16T23:39:03Z",
    "url": "https://github.com/sagemath/sage/issues/24698",
    "user": "https://github.com/fchapoton"
}
```
Future division made a doctest failure with the optional package plantri installed

```
sage -t --long src/sage/graphs/graph_generators.py
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    [u for u in list(gen)]  # optional plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
        [u for u in list(gen)]  # optional plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
    NameError: name 'planar' is not defined
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes == dual_planar_sizes                      # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
        planar_sizes == dual_planar_sizes                      # optional -- plantri
    NameError: name 'planar_sizes' is not defined
**********************************************************************
1 item had failures:
   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
    [140 tests, 4 failures, 29.80 s]
```

CC:  @tscrim @embray @jdemeyer

Branch/Commit: **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**

Reviewer: **Travis Scrimshaw**

Author: **Frédéric Chapoton**

Component: **graph theory**

_Issue created by migration from https://trac.sagemath.org/ticket/24698_





---

archive/issue_events_343529.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "milestone_number": null,
    "milestone_title": "sage-8.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343529"
}
```



---

archive/issue_events_343530.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
    "label_color": "eeeeee",
    "label_name": "c: graph theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343530"
}
```



---

archive/issue_events_343531.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343531"
}
```



---

archive/issue_events_343532.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "696969",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343532"
}
```



---

archive/issue_comments_375276.json:
```json
{
    "body": "Branch: **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375276",
    "user": "https://github.com/fchapoton"
}
```

Branch: **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**



---

archive/issue_events_343533.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:53:26Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343533"
}
```



---

archive/issue_comments_375277.json:
```json
{
    "body": "<div id=\"comment:1\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\"><code>a09e8a6</code></a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375277",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc"><code>a09e8a6</code></a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_comments_375278.json:
```json
{
    "body": "Commit: **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375278",
    "user": "https://github.com/fchapoton"
}
```

Commit: **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**



---

archive/issue_events_343534.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343534"
}
```



---

archive/issue_events_343535.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343535"
}
```



---

archive/issue_comments_375279.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nLGTM.",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375279",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:2" align="right">comment:2</div>

LGTM.



---

archive/issue_comments_375280.json:
```json
{
    "body": "Reviewer: **Travis Scrimshaw**",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375280",
    "user": "https://github.com/tscrim"
}
```

Reviewer: **Travis Scrimshaw**



---

archive/issue_events_343536.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343536"
}
```



---

archive/issue_events_343537.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343537"
}
```



---

archive/issue_comments_375281.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\nMerge conflict",
    "created_at": "2018-02-09T23:50:46Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375281",
    "user": "https://github.com/vbraun"
}
```

<div id="comment:3" align="right">comment:3</div>

Merge conflict



---

archive/issue_comments_375282.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1 +1,69 @@\n-coming from future division\n+Future division made a doctest failure with the optional package plantri installed\n+\n+```\n+sage -t --long src/sage/graphs/graph_generators.py\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    [u for u in list(gen)]  # optional plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n+        [u for u in list(gen)]  # optional plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+    NameError: name 'planar' is not defined\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes == dual_planar_sizes                      # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n+        planar_sizes == dual_planar_sizes                      # optional -- plantri\n+    NameError: name 'planar_sizes' is not defined\n+**********************************************************************\n+1 item had failures:\n+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n+    [140 tests, 4 failures, 29.80 s]\n+```\n``````\n",
    "created_at": "2018-02-13T19:23:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375282",
    "user": "https://github.com/videlec"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1 +1,69 @@
-coming from future division
+Future division made a doctest failure with the optional package plantri installed
+
+```
+sage -t --long src/sage/graphs/graph_generators.py
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    [u for u in list(gen)]  # optional plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
+        [u for u in list(gen)]  # optional plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+    NameError: name 'planar' is not defined
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes == dual_planar_sizes                      # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
+        planar_sizes == dual_planar_sizes                      # optional -- plantri
+    NameError: name 'planar_sizes' is not defined
+**********************************************************************
+1 item had failures:
+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
+    [140 tests, 4 failures, 29.80 s]
+```
``````




---

archive/issue_events_343538.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-13T19:23:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343538"
}
```



---

archive/issue_events_343539.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-13T19:23:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/p%3A%201%20%E2%80%93%20blocker",
    "label_color": "ff0000",
    "label_name": "p: 1 \u2013 blocker",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343539"
}
```



---

archive/issue_comments_375283.json:
```json
{
    "body": "<div id=\"comment:5\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834\"><code>d910d87</code></a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375283",
    "user": "https://github.com/videlec"
}
```

<div id="comment:5"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834"><code>d910d87</code></a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>




---

archive/issue_comments_375284.json:
```json
{
    "body": "Changed commit from **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)** to **[`d910d87`](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)**",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375284",
    "user": "https://github.com/videlec"
}
```

Changed commit from **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)** to **[`d910d87`](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)**



---

archive/issue_events_343540.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343540"
}
```



---

archive/issue_events_343541.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343541"
}
```



---

archive/issue_comments_375285.json:
```json
{
    "body": "Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)**",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375285",
    "user": "https://github.com/videlec"
}
```

Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)**



---

archive/issue_events_343542.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343542"
}
```



---

archive/issue_events_343543.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343543"
}
```



---

archive/issue_comments_375286.json:
```json
{
    "body": "Changed commit from **[`d910d87`](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)** to **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375286",
    "user": "https://github.com/videlec"
}
```

Changed commit from **[`d910d87`](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)** to **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**



---

archive/issue_comments_375287.json:
```json
{
    "body": "<div id=\"comment:7\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\"><code>a09e8a6</code></a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375287",
    "user": "https://github.com/videlec"
}
```

<div id="comment:7"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc"><code>a09e8a6</code></a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_events_343544.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343544"
}
```



---

archive/issue_events_343545.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343545"
}
```



---

archive/issue_comments_375288.json:
```json
{
    "body": "Changed branch from **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)** to **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375288",
    "user": "https://github.com/videlec"
}
```

Changed branch from **[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)** to **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)**



---

archive/issue_comments_375289.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\nReplying to [@vbraun](#comment:3):\n> Merge conflict\n\nSince this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...",
    "created_at": "2018-02-14T17:59:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375289",
    "user": "https://github.com/videlec"
}
```

<div id="comment:8" align="right">comment:8</div>

Replying to [@vbraun](#comment:3):
> Merge conflict

Since this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...



---

archive/issue_comments_375290.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nIt is supposed to have a conflict with Volker's private branch. But looking at the file there:\n\nhttps://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py\n\nI really do not see how there could be any conflict. This file was last modified 3 weeks ago.",
    "created_at": "2018-02-14T18:41:45Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375290",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:9" align="right">comment:9</div>

It is supposed to have a conflict with Volker's private branch. But looking at the file there:

https://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py

I really do not see how there could be any conflict. This file was last modified 3 weeks ago.



---

archive/issue_events_343546.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343546"
}
```



---

archive/issue_events_343547.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343547"
}
```



---

archive/issue_comments_375291.json:
```json
{
    "body": "<div id=\"comment:10\" align=\"right\">comment:10</div>\n\nLet's try it again then.",
    "created_at": "2018-02-14T22:46:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375291",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:10" align="right">comment:10</div>

Let's try it again then.



---

archive/issue_events_343548.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343548"
}
```



---

archive/issue_events_343549.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "d7195f1f358f0bbd7424a7c809914e0d144a43dc",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-343549"
}
```



---

archive/issue_comments_375292.json:
```json
{
    "body": "Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**",
    "created_at": "2018-02-16T23:39:03Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-375292",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)** to **[`a09e8a6`](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)**
